export enum ActionTypes {
  SIGNUP_USER,
  SIGNUP_USER_FULFILLED,
  LOGIN_USER,
  LOGIN_USER_FULFILLED,
  AUTH_FAILED,
  LOGOUT_USER,
  LOGOUT_USER_FULFILLED,
  FETCH_USER_DATA,
  FETCH_USER_DATA_FULFILLED,
}
